version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: wikitabia-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      wikitabia:
    ports:
      - "${DB_PORT}:5432"

  wikitabia-server:
    image: ${WIKITABIA_SERVER_IMAGE_NAME}:${WIKITABIA_SERVER_IMAGE_TAG}
    container_name: wikitabia-server
    restart: always
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:${DB_PORT}/${DB_NAME}"
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASS}
      #JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - postgres
    networks:
      wikitabia:
    ports:
      - "8080:8080"
      #- "5005:5005"

volumes:
  postgres:

networks:
  wikitabia:
